// 🧙‍♂️ Generated by LifeQuest RPG Transformation Script
// Class-specific mystical messages

export const ClassMessages = {
  "strategist": {
    "forging": "\"🔮 The Crystal Seer gazes into probability matrices...\"",
    "complete": "\"✨ The data streams have crystallized into perfect strategy cards!\"",
    "guidance": "\"📊 The analytical spirits whisper optimal paths...\""
  },
  "warrior": {
    "forging": "\"⚔️ The Battle Forge roars to life, tempering steel and spirit...\"",
    "complete": "\"🛡️ Your discipline has forged unbreakable habit cards!\"",
    "guidance": "\"💪 The war spirits guide you toward victory...\""
  },
  "creator": {
    "forging": "\"🎨 The Muses dance around the Inspiration Loom...\"",
    "complete": "\"🌈 Pure creativity has been woven into magnificent cards!\"",
    "guidance": "\"✨ The artistic spirits reveal new realms of possibility...\""
  },
  "connector": {
    "forging": "\"🤝 The Social Nexus resonates with connection energies...\"",
    "complete": "\"🌐 Bonds of fellowship have crystallized into network cards!\"",
    "guidance": "\"💫 The spirits of unity show paths to strengthen relationships...\""
  },
  "sage": {
    "forging": "\"🧘‍♂️ The Ancient Library opens its ethereal pages...\"",
    "complete": "\"📚 Timeless wisdom has materialized into enlightenment cards!\"",
    "guidance": "\"🌟 The eternal sages share insights from beyond time...\""
  }
};

export function getMysticMessage(userClass: string, messageType: string): string {
  const classMessages = ClassMessages[userClass as keyof typeof ClassMessages];
  if (classMessages && classMessages[messageType as keyof typeof classMessages]) {
    return classMessages[messageType as keyof typeof classMessages];
  }
  
  // Fallback genérico
  const fallbacks = {
    forging: "🔮 Ancient energies swirl, crafting your destiny...",
    complete: "✨ The mystical forces have woven powerful cards!",
    guidance: "🌟 The cosmic wisdom guides your path..."
  };
  
  return fallbacks[messageType as keyof typeof fallbacks] || "✨ The magic flows through you...";
}
